package com.mycompany.JDialogs;

import com.formdev.flatlaf.FlatClientProperties;
import com.mycompany.interfaces.DAOPacks;
import com.mycompany.interfaces.DAOPays;
import com.mycompany.models.Packs;
import com.mycompany.models.Pays;
import com.mycompany.models.Students;
import com.mycompany.DAOs.DAOPacksImp;
import com.mycompany.DAOs.DAOPaysImp;
import javax.swing.UIManager;

public class AddPack extends javax.swing.JDialog {
    private Students student = null;

    public AddPack(java.awt.Frame parent, boolean modal, Students student) {
        super(parent, modal);
        this.student = student;
        UIManager.put( "Button.arc", 25 );
        initComponents();
        init();
        loadPacks();
    }
    
    private void init(){
        setResizable(false);
        jPanel1.putClientProperty(FlatClientProperties.STYLE, ""
                + "arc:25;");
        
        Title.putClientProperty(FlatClientProperties.STYLE, ""
                + "font:bold +5;");
        
        NameLebel.putClientProperty(FlatClientProperties.STYLE, ""
                + "font:bold;");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bg = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        NameLebel = new javax.swing.JLabel();
        comboBox = new javax.swing.JComboBox<>();
        Botton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 104));

        bg.setBackground(new java.awt.Color(51, 51, 51));
        bg.setPreferredSize(new java.awt.Dimension(300, 104));

        Title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Title.setText("Nuevo Pack");

        NameLebel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NameLebel.setText("Pack :");

        comboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxItemStateChanged(evt);
            }
        });
        comboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxActionPerformed(evt);
            }
        });

        Botton.setText("Agregar");
        Botton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BottonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Title)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(NameLebel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(Botton)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title)
                .addGap(8, 8, 8)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLebel)
                    .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Botton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 104, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxActionPerformed

    }//GEN-LAST:event_comboBoxActionPerformed

    private void comboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxItemStateChanged

    }//GEN-LAST:event_comboBoxItemStateChanged

    private void BottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BottonActionPerformed
        int packId = comboBox.getSelectedIndex()+2;
        try{
            DAOPays daopays = new DAOPaysImp();
            DAOPacks daopacks = new DAOPacksImp();
            Packs pack = daopacks.selectPack(packId);
  
            Pays pay = new Pays();
            pay.setStudent(student);
            pay.setPack(pack);
            daopays.register(pay);
            
            javax.swing.JOptionPane.showMessageDialog(this,"Pago Exitoso","AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } catch(Exception e) {
            System.out.println(e.getMessage());
            javax.swing.JOptionPane.showMessageDialog(this,"Ocurrio un error al crear pago","AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        dispose();
    }//GEN-LAST:event_BottonActionPerformed
    
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddPack dialog = new AddPack(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    private void loadPacks(){
        try {
           comboBox.removeAllItems();
           DAOPacks dao = new DAOPacksImp();
           dao.list().forEach((u)-> comboBox.addItem(u.getName()));
       } catch (Exception e) {
           System.out.println("Error cargando packs: " + e.getMessage());
       }
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Botton;
    private javax.swing.JLabel NameLebel;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel bg;
    private javax.swing.JComboBox<String> comboBox;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
