package com.mycompany.JDialogs;

import com.formdev.flatlaf.FlatClientProperties;
import com.mycompany.DAOs.DAOPacksImp;
import com.mycompany.models.Packs;
import javax.swing.UIManager;

public class UpPack extends javax.swing.JDialog {
    private Packs pack;

    public UpPack(java.awt.Frame parent, boolean modal, Packs pack) {
        super(parent, modal);
        UIManager.put( "Button.arc", 25 );
        initComponents();
        init();
        
        if(pack != null){
            this.pack = pack;
            fillStudentData();
            Title.setText("Modificar Pack");
            button.setText("Modificar");
        }
        else{
            Title.setText("Nuevo Pack");
            button.setText("Agregar");
        }
    }
    
    private void init(){
        //setTitle("Nuevo Estudiante");
        setResizable(false);
        jPanel1.putClientProperty(FlatClientProperties.STYLE, ""
                + "arc:25;");
        
        Title.putClientProperty(FlatClientProperties.STYLE, ""
                + "font:bold +5;");
        
        NameLebel.putClientProperty(FlatClientProperties.STYLE, ""
                + "font:bold;");
        CantLabel.putClientProperty(FlatClientProperties.STYLE, ""
                + "font:bold;");
        PriceLabel.putClientProperty(FlatClientProperties.STYLE, ""
                + "font:bold;");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bg = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        NameLebel = new javax.swing.JLabel();
        CantLabel = new javax.swing.JLabel();
        PriceLabel = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        cantText = new javax.swing.JTextField();
        priceText = new javax.swing.JTextField();
        button = new com.mycompany.utils.ButtonAction();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 255));

        bg.setBackground(new java.awt.Color(51, 51, 51));
        bg.setPreferredSize(new java.awt.Dimension(300, 255));

        Title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Title.setText("Nuevo Pack");

        NameLebel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NameLebel.setText("Nombre:");

        CantLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CantLabel.setText("Cantidad de clases:");

        PriceLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PriceLabel.setText("Precio:");

        cantText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantTextActionPerformed(evt);
            }
        });

        button.setText("Agregar");
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CantLabel)
                            .addComponent(NameLebel)
                            .addComponent(PriceLabel)
                            .addComponent(Title)
                            .addComponent(cantText, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priceText, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(button, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title)
                .addGap(10, 10, 10)
                .addComponent(NameLebel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CantLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cantText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PriceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 255, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cantTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantTextActionPerformed

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
        String name = nameText.getText().trim();
        String cantTextValue = cantText.getText().trim();
        String priceTextValue = priceText.getText().trim();

        // Validaciones
        if (name.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,"El nombre no puede estar vacío","AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        if (cantTextValue.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,"La cantidad no puede estar vacio","AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        if (!isNumeric(cantTextValue)) {
            javax.swing.JOptionPane.showMessageDialog(this,"La cantidad debe ser un número válido","AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        if (!isNumeric(priceTextValue)) {
            javax.swing.JOptionPane.showMessageDialog(this,"El precio debe ser un número válido","AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        int cant = Integer.parseInt(cantTextValue);
        int price = Integer.parseInt(priceTextValue);
        
        try{
            DAOPacksImp dao = new DAOPacksImp();
            
            if(pack == null){
                Packs pack = new Packs();
                pack.setName(name);
                pack.setCant_class(cant);
                pack.setPrice(price);
                


                dao.register(pack);
                javax.swing.JOptionPane.showMessageDialog(this,"Registro Exitoso","AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                pack.setName(name);
                pack.setCant_class(cant);
                pack.setPrice(price);
                
                dao.modify(pack);
                javax.swing.JOptionPane.showMessageDialog(this,"Modificación Exitosa","AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
            
        } catch(Exception e) {
            if (pack == null){
                javax.swing.JOptionPane.showMessageDialog(this,"Ocurrio un error al registrar","AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
            else{
                javax.swing.JOptionPane.showMessageDialog(this,"Ocurrio un error al modificar","AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
            System.out.println(e.getMessage());
        }
        dispose();
    }//GEN-LAST:event_buttonActionPerformed
    
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UpPack dialog = new UpPack(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CantLabel;
    private javax.swing.JLabel NameLebel;
    private javax.swing.JLabel PriceLabel;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel bg;
    private com.mycompany.utils.ButtonAction button;
    private javax.swing.JTextField cantText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameText;
    private javax.swing.JTextField priceText;
    // End of variables declaration//GEN-END:variables

    private boolean isNumeric(String str) {
        try {
            Long.valueOf(str); // Intentamos convertir a un número largo
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    private void fillStudentData() {
        nameText.setText(pack.getName());
        cantText.setText(String.valueOf(pack.getCant_class()));
        priceText.setText(String.valueOf(pack.getPrice()));
    }
}
