package com.mycompany.JDialogs;

import com.formdev.flatlaf.FlatClientProperties;
import com.mycompany.interfaces.DAOStudents;
import com.mycompany.models.Students;
import com.mycompany.DAOs.DAOStudentsImp;
import javax.swing.UIManager;

public class UpUser extends javax.swing.JDialog {
    private Students student = null;

    public UpUser(java.awt.Frame parent, boolean modal, Students student) {
        super(parent, modal);
        UIManager.put( "Button.arc", 25 );
        initComponents();
        init();
        
        if(student != null){
            this.student = student;
            fillStudentData();
            Title.setText("Modificar Estudiante");
            button.setText("Modificar");
        }
        else{
            Title.setText("Nuevo Estudiante");
            button.setText("Agregar");
        }
    }
    
    private void init(){
        //setTitle("Nuevo Estudiante");
        setResizable(false);
        jPanel1.putClientProperty(FlatClientProperties.STYLE, ""
                + "arc:25;");
        
        Title.putClientProperty(FlatClientProperties.STYLE, ""
                + "font:bold +5;");
        
        NameLebel.putClientProperty(FlatClientProperties.STYLE, ""
                + "font:bold;");
        EmailLabel.putClientProperty(FlatClientProperties.STYLE, ""
                + "font:bold;");
        DNILabel.putClientProperty(FlatClientProperties.STYLE, ""
                + "font:bold;");
        PhoneLabel.putClientProperty(FlatClientProperties.STYLE, ""
                + "font:bold;");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bg = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        NameLebel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        DNILabel = new javax.swing.JLabel();
        PhoneLabel = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        emailText = new javax.swing.JTextField();
        DNIText = new javax.swing.JTextField();
        phoneText = new javax.swing.JTextField();
        button = new com.mycompany.utils.ButtonAction();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 315));

        bg.setBackground(new java.awt.Color(51, 51, 51));
        bg.setPreferredSize(new java.awt.Dimension(300, 315));

        Title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Title.setText("Nuevo Estudiante");

        NameLebel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NameLebel.setText("Nombre:");

        EmailLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EmailLabel.setText("Email:");

        DNILabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DNILabel.setText("DNI:");

        PhoneLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PhoneLabel.setText("Telefono:");

        emailText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextActionPerformed(evt);
            }
        });

        phoneText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneTextActionPerformed(evt);
            }
        });

        button.setText("Agregar");
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmailLabel)
                            .addComponent(NameLebel)
                            .addComponent(DNILabel)
                            .addComponent(PhoneLabel)
                            .addComponent(Title)
                            .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DNIText, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneText, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(button, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title)
                .addGap(10, 10, 10)
                .addComponent(NameLebel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmailLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DNILabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DNIText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PhoneLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phoneText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 315, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextActionPerformed

    private void phoneTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneTextActionPerformed

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
        String name = nameText.getText().trim();
        String email = emailText.getText().trim();
        String dni = DNIText.getText().trim();
        String phone = phoneText.getText().trim();

        // Validaciones
        if (name.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,"El nombre no puede estar vacío","AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        if (email.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,"El correo electrónico no puede estar vacio","AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        if (!isNumeric(dni)) {
            javax.swing.JOptionPane.showMessageDialog(this,"El DNI debe ser un número válido","AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        if (!isNumeric(phone) || phone.length() < 8) {
            javax.swing.JOptionPane.showMessageDialog(this,"El número de teléfono debe ser un número válido de al menos 8 dígitos","AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        try{
            DAOStudents dao = new DAOStudentsImp();
            
            if(student == null){
                Students student = new Students();
                student.setName(name);
                student.setEmail(email);
                student.setDNI(dni);
                student.setPhone_Number(phone);


                dao.register(student);
                javax.swing.JOptionPane.showMessageDialog(this,"Registro Exitoso","AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                student.setName(name);
                student.setEmail(email);
                student.setDNI(dni);
                student.setPhone_Number(phone);

                dao.modify(student);
                javax.swing.JOptionPane.showMessageDialog(this,"Modificación Exitosa","AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
            
        } catch(Exception e) {
            if (student == null){
                javax.swing.JOptionPane.showMessageDialog(this,"Ocurrio un error al registrar","AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
            else{
                javax.swing.JOptionPane.showMessageDialog(this,"Ocurrio un error al modificar","AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
            System.out.println(e.getMessage());
        }
        dispose();
    }//GEN-LAST:event_buttonActionPerformed
    
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UpUser dialog = new UpUser(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DNILabel;
    private javax.swing.JTextField DNIText;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JLabel NameLebel;
    private javax.swing.JLabel PhoneLabel;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel bg;
    private com.mycompany.utils.ButtonAction button;
    private javax.swing.JTextField emailText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameText;
    private javax.swing.JTextField phoneText;
    // End of variables declaration//GEN-END:variables

    private boolean isNumeric(String str) {
        try {
            Long.valueOf(str); 
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    private void fillStudentData() {
        nameText.setText(student.getName());
        emailText.setText(student.getEmail());
        DNIText.setText(student.getDNI());
        phoneText.setText(student.getPhone_number());
    }
}
