package com.mycompany.proyectodb;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.formdev.flatlaf.intellijthemes.FlatDarkFlatIJTheme;
import com.mycompany.views.*;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.UIManager;
import java.time.LocalDate;
import javax.swing.ButtonGroup;
import javax.swing.JPanel;

public class Managment extends javax.swing.JFrame {

    public Managment() {
        initComponents();
        InitStyles();
        SetDate();
        InitContent();
        
    }
    
    private void InitContent() {
        classesButton.setSelected(true);
        ShowJPanel(new Classes());
    }
    
    public void ShowJPanel(JPanel p) {
        p.setSize(820, 540);
        p.setLocation(0,0);
        
        Content.removeAll();
        Content.setLayout(new BorderLayout());
        Content.add(p, BorderLayout.CENTER);
        Content.revalidate();
        Content.repaint();
    }
    
    private void SetDate() {
        // Obtener la fecha actual
        LocalDate now = LocalDate.now();
        int year = now.getYear();
        int day = now.getDayOfMonth();
        int month = now.getMonthValue();

        // Definir nombres de los meses
        String[] meses = {"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"};

        // Obtener el día de la semana
        String[] diasSemana = {"Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"};
        String diaSemana = diasSemana[now.getDayOfWeek().getValue() - 1]; // Ajustar índice para la semana

        // Mostrar el texto en el JLabel con el día de la semana
        dateText.setText("Hoy es " + diaSemana + ", " + day + " de " + meses[month - 1] + " de " + year);
    }

    
    private void InitStyles(){
        message.putClientProperty( "FlatLaf.style", "font: bold $h1.regular.font" );
        message.setForeground(Color.white);
        classesButton.setForeground(Color.white);
        salaryButton.setForeground(Color.white);
        packsButton.setForeground(Color.white);
        backButton.setForeground(Color.white);
        ButtonGroup group = new ButtonGroup();
        group.add(classesButton);
        group.add(salaryButton);
        group.add(packsButton);
        group.add(backButton);

        classesButton.setIcon(new FlatSVGIcon("images/calendar.svg"));
        salaryButton.setIcon(new FlatSVGIcon("images/wallet.svg"));
        packsButton.setIcon(new FlatSVGIcon("images/package.svg"));
        backButton.setIcon(new FlatSVGIcon("images/back.svg"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        classesButton = new javax.swing.JToggleButton();
        salaryButton = new javax.swing.JToggleButton();
        backButton = new javax.swing.JToggleButton();
        mainButton1 = new javax.swing.JToggleButton();
        packsButton = new javax.swing.JToggleButton();
        Header = new javax.swing.JPanel();
        message = new javax.swing.JLabel();
        dateText = new javax.swing.JLabel();
        Content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(51, 51, 51));
        Background.setForeground(new java.awt.Color(153, 153, 153));

        Menu.setBackground(new java.awt.Color(51, 51, 51));
        Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo2.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        Menu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 220, 200));

        classesButton.setBackground(new java.awt.Color(51, 51, 51));
        classesButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        classesButton.setText("Clases");
        classesButton.setBorderPainted(false);
        classesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        classesButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        classesButton.setIconTextGap(8);
        classesButton.setRequestFocusEnabled(false);
        classesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classesButtonActionPerformed(evt);
            }
        });
        Menu.add(classesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 200, 40));

        salaryButton.setBackground(new java.awt.Color(51, 51, 51));
        salaryButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        salaryButton.setText("Egresos");
        salaryButton.setBorderPainted(false);
        salaryButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salaryButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        salaryButton.setIconTextGap(8);
        salaryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryButtonActionPerformed(evt);
            }
        });
        Menu.add(salaryButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 200, 40));

        backButton.setBackground(new java.awt.Color(51, 51, 51));
        backButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backButton.setText("Salir");
        backButton.setBorderPainted(false);
        backButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        backButton.setIconTextGap(8);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        Menu.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 200, 40));

        mainButton1.setBackground(new java.awt.Color(51, 51, 51));
        mainButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mainButton1.setText("Clases");
        mainButton1.setBorderPainted(false);
        mainButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mainButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mainButton1.setRequestFocusEnabled(false);
        mainButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainButton1ActionPerformed(evt);
            }
        });
        Menu.add(mainButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 200, 40));

        packsButton.setBackground(new java.awt.Color(51, 51, 51));
        packsButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        packsButton.setText("Packs");
        packsButton.setBorderPainted(false);
        packsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        packsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        packsButton.setIconTextGap(8);
        packsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                packsButtonActionPerformed(evt);
            }
        });
        Menu.add(packsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 200, 40));

        Header.setBackground(new java.awt.Color(51, 51, 51));
        Header.setPreferredSize(new java.awt.Dimension(832, 60));

        message.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        message.setText("Gestion Del Estudio");
        message.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        dateText.setText("Hoy es {dayname} {day} de {month} de {year}");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addComponent(dateText, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(262, Short.MAX_VALUE))
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateText))
        );

        Content.setBackground(new java.awt.Color(102, 102, 102));
        Content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void salaryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryButtonActionPerformed
        ShowJPanel(new Salary());
    }//GEN-LAST:event_salaryButtonActionPerformed

    private void classesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classesButtonActionPerformed
        ShowJPanel(new Classes());
    }//GEN-LAST:event_classesButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.setVisible(false);
        this.dispose();
        Dashboard main = new Dashboard();
        main.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void mainButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mainButton1ActionPerformed

    private void packsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_packsButtonActionPerformed
        ShowJPanel(new Pack());
    }//GEN-LAST:event_packsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatDarkFlatIJTheme.setup();
        UIManager.put( "Component.focusWidth", 1 );
        UIManager.put( "Button.arc", 25 );

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Managment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel Content;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Menu;
    private javax.swing.JToggleButton backButton;
    private javax.swing.JToggleButton classesButton;
    private javax.swing.JLabel dateText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton mainButton1;
    private javax.swing.JLabel message;
    private javax.swing.JToggleButton packsButton;
    private javax.swing.JToggleButton salaryButton;
    // End of variables declaration//GEN-END:variables
}
